# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}

    strategy:
      matrix:
        node-version: [12, 14, 15]

    services:
      redis:
        image: redis
        # wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      REDIS_URL: redis://redis:6379
      DISABLE_TELEMETRY: true

    defaults:
      run:
        working-directory: quirrel

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm test -- --coverage
      - run: curl -Ls https://coverage.codacy.com/get.sh > codacy.sh && chmod +x codacy.sh
      - run: ./codacy.sh report --coverage-reports coverage/lcov.info --partial --prefix quirrel --token ${{ secrets.CODACY_PROJECT_TOKEN }}
        if: ${{ matrix.node-version == 14 }}

  dev-ui-test:
    name: Development UI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: development-ui
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - run: npm ci
      - run: npm run test:ci
      - run: curl -Ls https://coverage.codacy.com/get.sh > codacy.sh && chmod +x codacy.sh
      - run: ./codacy.sh report --coverage-reports coverage/lcov.info --partial --prefix development-ui --token ${{ secrets.CODACY_PROJECT_TOKEN }}

  finish-coverage:
    needs:
      - build
      - dev-ui-test
    runs-on: ubuntu-latest
    steps:
      - run: curl -Ls https://coverage.codacy.com/get.sh > codacy.sh && chmod +x codacy.sh
      - run: ./codacy.sh final --token ${{ secrets.CODACY_PROJECT_TOKEN }}

  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          path: quirrel
          username: skn0tt
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          repository: quirrel-dev/quirrel
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true

  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_PROJECT_PATH: quirrel
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
